// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_tempvlaue;
extern lv_obj_t * ui_temp;
void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_gpuvlaue;
extern lv_obj_t * ui_gpu;
void ui_event_Arc4(lv_event_t * e);
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_memvlaue;
extern lv_obj_t * ui_mem;
void ui_event_Arc5(lv_event_t * e);
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_cpuvlaue;
extern lv_obj_t * ui_cpu;

extern lv_obj_t * ui_time;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
