// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Demo01

#ifndef _DEMO01_UI_H
#define _DEMO01_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

typedef struct page
{
    lv_obj_t * screen;
}page_t;

struct f_page
{
    page_t base;
    lv_obj_t * time;
    lv_obj_t * year;
    lv_obj_t * week;
    lv_obj_t * weather;
};

typedef struct s_show
{
    lv_obj_t *arc;
    lv_obj_t *name;
    lv_obj_t *value;
}s_show_t;

struct s_page
{
    page_t base;
    s_show_t cpu;
    s_show_t gpu;
    s_show_t mem;
    s_show_t temp;
};

// Font
LV_FONT_DECLARE(font_alipuhui20);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_Screen2_screen_init(void);
extern struct f_page first_page;
extern struct s_page winner_page;
// extern lv_obj_t * ui_Screen1;
// extern lv_obj_t * ui_time;
// extern lv_obj_t * ui_year;
// extern lv_obj_t * ui____initial_actions0;

void ui_event_temp(lv_event_t * e);

void ui_event_gpu(lv_event_t * e);

void ui_event_mem(lv_event_t * e);

void ui_event_cpu(lv_event_t * e);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
