// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project
#include <stdio.h>

#include "ui.h"

struct s_page winner_page;

void ui_member_init(lv_obj_t *parent, lv_obj_t ***mem_arc, lv_obj_t ***mem_name, lv_obj_t ***mem_value, lv_event_cb_t event_cb, lv_color_t color, const char *name)
{
    *mem_arc = lv_arc_create(parent);
    lv_obj_set_width(*mem_arc, 100);
    lv_obj_set_height(*mem_arc, 100);
    lv_obj_set_align(*mem_arc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(*mem_arc, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
    lv_obj_set_flex_align(*mem_arc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(*mem_arc, 50);
    lv_arc_set_rotation(*mem_arc, 1);
    lv_obj_set_style_arc_width(*mem_arc, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_add_event_cb(*mem_arc, arc_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    lv_obj_set_style_arc_color(*mem_arc, color, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(*mem_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(*mem_arc, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(*mem_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(*mem_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    *mem_name = lv_label_create(*mem_arc);
    lv_obj_set_width(*mem_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(*mem_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(*mem_name, LV_ALIGN_CENTER);
    lv_label_set_text(*mem_name, name);

    *mem_value = lv_label_create(*mem_arc);
    lv_obj_set_width(*mem_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(*mem_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(*mem_value, -237);
    lv_obj_set_y(*mem_value, 42);
    lv_label_set_text(*mem_value, "50");

    lv_obj_add_event_cb(*mem_arc, event_cb, LV_EVENT_ALL, NULL);
}
void ui_Screen2_screen_init(void)
{
    winner_page.base.screen = lv_obj_create(NULL);
    lv_obj_clear_flag(winner_page.base.screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(winner_page.base.screen, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
    lv_obj_set_flex_align(winner_page.base.screen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);

    ui_member_init(winner_page.base.screen, &winner_page.mem.arc, &winner_page.mem.name, &winner_page.mem.value, ui_event_mem, lv_color_hex(0xF953A4), "mem");
    ui_member_init(winner_page.base.screen, &winner_page.gpu.arc, &winner_page.gpu.name, &winner_page.gpu.value, ui_event_gpu, lv_color_hex(0x3BFF00), "gpu");
    ui_member_init(winner_page.base.screen, &winner_page.temp.arc, &winner_page.temp.name, &winner_page.temp.value, ui_event_temp, lv_color_hex(0xF9F453), "temp");
    ui_member_init(winner_page.base.screen, &winner_page.cpu.arc, &winner_page.cpu.name, &winner_page.cpu.value, ui_event_cpu, lv_color_hex(0x53F9F8), "cpu");
}
