// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.5.0
// // LVGL version: 8.3.6
// // Project name: SquareLine_Project
// #include <stdio.h>

// #include "ui.h"

// static void arc_event_cb(lv_event_t *e)
// {
//     // 获取事件触发的对象
//     lv_obj_t *arc = lv_event_get_target(e);

//     // 获取 arc 的当前值
//     int32_t value = lv_arc_get_value(arc);

//     // 更新标签显示内容
//     char buf[8];  // 缓存区大小足够存放数值
//     snprintf(buf, sizeof(buf), "%ld", value); // 将数值转换为字符串
//     lv_label_set_text(ui_tempvlaue, buf);

//     // 可选：调整标签的位置
//     lv_obj_align_to(ui_tempvlaue, arc, LV_ALIGN_CENTER, 0, 0);
// }


// void ui_Screen1_screen_init(void)
// {
//     ui_Screen1 = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
//     lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);

//     ui_Arc2 = lv_arc_create(ui_Screen1);
//     lv_obj_set_width(ui_Arc2, 100);
//     lv_obj_set_height(ui_Arc2, 100);
//     lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
//     lv_obj_set_flex_flow(ui_Arc2, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
//     lv_obj_set_flex_align(ui_Arc2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
//     lv_arc_set_value(ui_Arc2, 50);
//     lv_arc_set_rotation(ui_Arc2, 1);
//     lv_obj_set_style_arc_width(ui_Arc2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_add_event_cb(ui_Arc2, arc_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

//     lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xF9F453), LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_width(ui_Arc2, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

//     lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

//     ui_tempvlaue = lv_label_create(ui_Arc2);
//     lv_obj_set_width(ui_tempvlaue, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_tempvlaue, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_tempvlaue, -237);
//     lv_obj_set_y(ui_tempvlaue, 42);
//     lv_label_set_text(ui_tempvlaue, "50");

//     ui_temp = lv_label_create(ui_Arc2);
//     lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_temp, "tem");

//     ui_Arc3 = lv_arc_create(ui_Screen1);
//     lv_obj_set_width(ui_Arc3, 100);
//     lv_obj_set_height(ui_Arc3, 100);
//     lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
//     lv_obj_set_flex_flow(ui_Arc3, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
//     lv_obj_set_flex_align(ui_Arc3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
//     lv_arc_set_value(ui_Arc3, 50);
//     lv_arc_set_rotation(ui_Arc3, 1);
//     lv_obj_set_style_arc_width(ui_Arc3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x79F953), LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_width(ui_Arc3, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

//     lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

//     ui_gpuvlaue = lv_label_create(ui_Arc3);
//     lv_obj_set_width(ui_gpuvlaue, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_gpuvlaue, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_gpuvlaue, -237);
//     lv_obj_set_y(ui_gpuvlaue, 42);
//     lv_label_set_text(ui_gpuvlaue, "50");

//     ui_gpu = lv_label_create(ui_Arc3);
//     lv_obj_set_width(ui_gpu, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_gpu, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_align(ui_gpu, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_gpu, "gpu");

//     ui_Arc4 = lv_arc_create(ui_Screen1);
//     lv_obj_set_width(ui_Arc4, 100);
//     lv_obj_set_height(ui_Arc4, 100);
//     lv_obj_set_x(ui_Arc4, -10);
//     lv_obj_set_y(ui_Arc4, -18);
//     lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
//     lv_obj_set_flex_flow(ui_Arc4, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
//     lv_obj_set_flex_align(ui_Arc4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
//     lv_arc_set_value(ui_Arc4, 50);
//     lv_arc_set_rotation(ui_Arc4, 1);
//     lv_obj_set_style_arc_width(ui_Arc4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0xF953A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_width(ui_Arc4, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

//     lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

//     ui_memvlaue = lv_label_create(ui_Arc4);
//     lv_obj_set_width(ui_memvlaue, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_memvlaue, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_memvlaue, -237);
//     lv_obj_set_y(ui_memvlaue, 42);
//     lv_label_set_text(ui_memvlaue, "50");

//     ui_mem = lv_label_create(ui_Arc4);
//     lv_obj_set_width(ui_mem, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_mem, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_align(ui_mem, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_mem, "mem");

//     ui_Arc5 = lv_arc_create(ui_Screen1);
//     lv_obj_set_width(ui_Arc5, 100);
//     lv_obj_set_height(ui_Arc5, 100);
//     lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
//     lv_obj_set_flex_flow(ui_Arc5, LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
//     lv_obj_set_flex_align(ui_Arc5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
//     lv_arc_set_value(ui_Arc5, 50);
//     lv_arc_set_rotation(ui_Arc5, 1);
//     lv_obj_set_style_arc_width(ui_Arc5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0x53F9F8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
//     lv_obj_set_style_arc_width(ui_Arc5, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

//     lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Arc5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

//     ui_cpuvlaue = lv_label_create(ui_Arc5);
//     lv_obj_set_width(ui_cpuvlaue, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_cpuvlaue, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_cpuvlaue, -237);
//     lv_obj_set_y(ui_cpuvlaue, 42);
//     lv_label_set_text(ui_cpuvlaue, "50");

//     ui_cpu = lv_label_create(ui_Arc5);
//     lv_obj_set_width(ui_cpu, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_cpu, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_align(ui_cpu, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_cpu, "cpu");

//     lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Arc3, ui_event_Arc3, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Arc4, ui_event_Arc4, LV_EVENT_ALL, NULL);
//     lv_obj_add_event_cb(ui_Arc5, ui_event_Arc5, LV_EVENT_ALL, NULL);

//     ui_time = lv_label_create(ui_Screen1);
//     lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_time, "2025:02:01   23:00:00");

// }
