// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Demo01

#include "ui.h"

// LV_FONT_DECLARE(font_alipuhui20);

struct f_page first_page;

void ui_Screen1_screen_init(void)
{
    first_page.base.screen = lv_obj_create(NULL);
    lv_obj_clear_flag(first_page.base.screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(first_page.base.screen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(first_page.base.screen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    first_page.time = lv_label_create(first_page.base.screen);
    lv_obj_set_width(first_page.time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(first_page.time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(first_page.time, LV_ALIGN_CENTER);
    lv_label_set_text(first_page.time, "你好世界");
    // lv_obj_set_style_text_align(first_page.time, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(first_page.time, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    first_page.year = lv_label_create(first_page.base.screen);
    lv_obj_set_width(first_page.year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(first_page.year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(first_page.year, LV_ALIGN_CENTER);
    lv_label_set_text(first_page.year, "2023-08-08");
    // lv_obj_set_style_text_align(first_page.year, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(first_page.year, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    first_page.week = lv_label_create(first_page.base.screen);
    lv_obj_set_width(first_page.week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(first_page.week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(first_page.week, LV_ALIGN_CENTER);
    lv_label_set_text(first_page.week, "周三\n天气: 晴");
    // lv_obj_set_style_text_align(first_page.year, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(first_page.week, &font_alipuhui20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
