// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_cpu = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_cpu, 320);
    lv_obj_set_height(ui_cpu, 100);
    lv_obj_set_align(ui_cpu, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cpu, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cpu, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_cpu);
    lv_obj_set_width(ui_Arc1, 80);
    lv_obj_set_height(ui_Arc1, 80);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Arc1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);
    lv_obj_set_style_arc_width(ui_Arc1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Arc1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "cpu");

    ui_Label6 = lv_label_create(ui_Arc1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "50");

    ui_Chart2 = lv_chart_create(ui_cpu);
    lv_obj_set_width(ui_Chart2, 220);
    lv_obj_set_height(ui_Chart2, 100);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart2, 20);
    lv_chart_set_div_line_count(ui_Chart2, 10, 22);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x26FF00),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 10, 20, 30, 10, 100 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0x08FF00), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_Chart2, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Chart2, true, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chart2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chart2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chart2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chart2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Chart2, 50, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Chart2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_dir(ui_Chart2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Chart2, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_Chart2, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 0, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart2, lv_color_hex(0x808080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2, 0, LV_PART_TICKS | LV_STATE_DEFAULT);


}
