// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc6 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Arc6, 100);
    lv_obj_set_height(ui_Arc6, 100);
    lv_obj_set_x(ui_Arc6, -80);
    lv_obj_set_y(ui_Arc6, -60);
    lv_obj_set_align(ui_Arc6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Arc6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc6, 50);
    lv_obj_set_style_arc_width(ui_Arc6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc6, lv_color_hex(0xD900FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc6, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc6, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc6, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Arc6);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -81);
    lv_obj_set_y(ui_Label8, -64);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "cpu");

    ui_Label9 = lv_label_create(ui_Arc6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -81);
    lv_obj_set_y(ui_Label9, -30);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "50");

    ui_Arc3 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Arc3, 100);
    lv_obj_set_height(ui_Arc3, 100);
    lv_obj_set_x(ui_Arc3, 80);
    lv_obj_set_y(ui_Arc3, -60);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Arc3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc3, 50);
    lv_obj_set_style_arc_width(ui_Arc3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xD900FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Arc3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -81);
    lv_obj_set_y(ui_Label3, -64);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "cpu");

    ui_Label1 = lv_label_create(ui_Arc3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -81);
    lv_obj_set_y(ui_Label1, -30);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "50");

    ui_Arc4 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Arc4, 100);
    lv_obj_set_height(ui_Arc4, 100);
    lv_obj_set_x(ui_Arc4, -80);
    lv_obj_set_y(ui_Arc4, 60);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Arc4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc4, 50);
    lv_obj_set_style_arc_width(ui_Arc4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0xD900FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc4, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Arc4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -81);
    lv_obj_set_y(ui_Label4, -64);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "cpu");

    ui_Label5 = lv_label_create(ui_Arc4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -81);
    lv_obj_set_y(ui_Label5, -30);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "50");

    ui_Arc5 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Arc5, 100);
    lv_obj_set_height(ui_Arc5, 100);
    lv_obj_set_x(ui_Arc5, 80);
    lv_obj_set_y(ui_Arc5, 60);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Arc5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Arc5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc5, 50);
    lv_obj_set_style_arc_width(ui_Arc5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0xD900FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc5, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Arc5);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -81);
    lv_obj_set_y(ui_Label10, -64);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "cpu");

    ui_Label11 = lv_label_create(ui_Arc5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -81);
    lv_obj_set_y(ui_Label11, -30);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "50");


}
